---
image: gitpod/workspace-base
# Commands that will run on workspace start 
tasks: 
    - name: Setup, Install & Build 
      before: apt install cargo redis-server nodejs npm -y && cargo test
      init: cargo install cargo-watch 
      command: redis-server --port 8080 & cargo watch -q -w "." -x "run" 
# Ports to expose on workspace startup 
ports: 
    - name: Website 
      description: Website Preview 
      port: 8080 
      onOpen: open-preview
# vscode IDE setup
vscode: 
   extensions: 
    - vadimcn.vscode-lldb
    - cschleiden.vscode-github-actions
    - rust-lang.rust
    - bungcip.better-toml
    - serayuzgur.crates
    - usernamehw.errorlens
    - DavidAnson.vscode-markdownlint
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - dbaeumer.vscode-eslint
    - evgeniypeshkov.syntax-highlighter
    - redhat.vscode-yaml
    - ms-azuretools.vscode-docker
    - Catppuccin.catppuccin-vsc
    - PKief.material-icon-theme
    - oderwat.indent-rainbow
    - formulahendry.auto-rename-tag
    - eamodio.gitlens
github: 
   prebuilds: 
      master: true 
      branches: true 
      pullRequests: true 
      pullRequestsFromForks: true 
      addCheck: true 
      addComment: false 
      addBadge: true
