version: 2.1

workflows:
  main:
    jobs:
      - sync-to-huggingface:
          context:
            - HuggingFace
          filters:
            branches:
              only:
                - hf-rolling

jobs:
  sync-to-huggingface:
    docker:
      - image: alpine
    resource_class: small
    steps:
      - run: 
          name: install git
          command: apk update && apk add openssh-client git
      - checkout
      - run:
          name: push to Huggingface hub
          command: |
                  git config http.postBuffer 524288000
                  git config user.email "<mo.alamin655@gmail.com>" 
                  git config user.name "<alamin655>" 
                  git push -f https://alamin655:${HF_PERSONAL_TOKEN}@huggingface.co/spaces/alamin655/spacex hf-rolling:main
