name: Contributors

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Contributors List
        uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          round: false
