name: Contributors List

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 1 * * *"

jobs:
  contributors:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
          ref: rolling
          
      - name: Generate contributors list
        run: |
          echo '<a href="https://github.com/neon-mmd/websurfx/graphs/contributors">' >> contributors_list.html
          echo '  <img src="https://contrib.rocks/image?repo=neon-mmd/websurfx" />' >> contributors_list.html
          echo '</a>' >> contributors_list.html
        shell: bash
      
      - name: Commit & PR
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: contributors_list.html
          commit-message: 'chore: update contributors-list'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: workflow/update-contributors-list
          base: rolling
          delete-branch: true
          title: 'chore: update contributors-list'
          body: |
            Automated update to `contributors_list.html`
