name: Contributors
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - rolling
      - TEST
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          round: true
