name: Contributors List

on:
  workflow_dispatch:

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@master
        with:
          use_username: true
          image_size: 80
          readme_path: README.md
          columns_per_row: 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
