name: Sync to Hugging Face hub
on:
  push:
    branches: [hf-rolling]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git git pull --allow-unrelated-histories https://alamin655:$HF_TOKEN@huggingface.co/spaces/alamin655/spacex main
        run: git push https://alamin655:$HF_TOKEN@huggingface.co/spaces/alamin655/spacex hf-rolling:main
