name: Release rolling image

on:
  push:
    branches:
      - "docker"

env:
  CARGO_TERM_COLOR: always

jobs:
  release_image:
    strategy:
      fail-fast: false
      matrix:
        cache:
          - memory
          - redis
          - hybrid
          - no-cache

    name: Release ${{ matrix.cache }} image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache register
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-cache
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:          
          username: alamin655
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Fetch version from another repository
        run: |
          GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          VERSION=$(gh api repos/neon-mmd/websurfx/releases/latest --jq '.tag_name')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Info
        run: |
          echo $VERSION
      - name: Create buildx multiarch
        run: docker buildx create --use --name=buildx-multi-arch --driver=docker-container --driver-opt=network=host
      - name: Modify Cache variable
        run: | 
          sed -i "s/ARG CACHE=[a-z]*/ARG CACHE=${{ matrix.cache }}/g" Dockerfile
      - name: Publish image
        run: docker buildx build --builder=buildx-multi-arch --platform=linux/amd64,linux/arm64 --build-arg CACHE=${{ matrix.cache }} --push -t alamin655/websurfx:${{ matrix.cache }}-$VERSION -t alamin655/websurfx:${{matrix.cache}} -f Dockerfile .
      - name: Publish latest
        if: ${{ matrix.cache }} == 'hybrid'
        run: docker buildx build --builder=buildx-multi-arch --platform=linux/amd64,linux/arm64 --build-arg CACHE=${{ matrix.cache }} --push -t alamin655/websurfx:latest -f Dockerfile .
