name: Bump release version
on:
  pull_request:
    branches: [rolling]
    types:
      - closed

permissions:
  contents: write

concurrency: production

jobs:
  build:
    name: Create Release  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name:  'Automated Version Bump'
        id: version-bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE: false
          RELEASE_BRANCHES: rolling,stable
        with:
          tag_name: ${{ steps.version-bump.outputs.new_tag }}
          release_name: ${{ steps.version-bump.outputs.new_tag }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          
          draft: false
          prerelease: false

