name: Bump release version
on:
  pull_request:
    branches: [rolling]
    types:
      - closed

permissions:
  contents: write

concurrency: production

jobs:
  build:
    name: bump tag version and release  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }} ## this seems to be required due to https://github.com/anothrNick/github-tag-action/issues/266
          fetch-depth: 0
      - name:  'Automated Version Bump'
        id: version-bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          PRERELEASE: false
          DEFAULT_BRANCH: rolling
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          name: ${{ steps.version-bump.outputs.new_tag }}
          tag_name: ${{ steps.version-bump.outputs.new_tag }}
          prerelease: false
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

