name: Bump release version
on:
  pull_request:
    branches: [rolling]
    types:
      - closed

permissions:
  contents: write

concurrency: production

jobs:
  build:
    name: Create Release  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name:  'Automated Version Bump'
        id: version-bump
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording:  'MAJOR,major-change'
          minor-wording:  'feat,'
          patch-wording:  'patch,fix,build,chore,ci,docs,style,refactor,perf,test'     # Providing patch-wording will override commits
          tag-prefix:  'v'
          default: patch
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version-bump.outputs.newTag }}
          release_name: ${{ steps.version-bump.outputs.newTag }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

